CREATE TABLE `soldiers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `soldierName` varchar(128) NOT NULL,
  `soldierSurname` varchar(128) NOT NULL,
  `birthday` DATE NOT NULL,
  `sex` varchar(64) NOT NULL,
  `phone` varchar(64) NOT NULL,
  `email` varchar(255) NOT NULL,
  `code` int(6) NOT NULL,
  `city` varchar(64) NOT NULL,
  `street` varchar(64) NOT NULL,
  `numberHouse` varchar(64) NOT NULL,
  `militaryRank` varchar(255) NOT NULL,
  `jwNumber` varchar(64) NOT NULL,
  `missions` varchar(255) NOT NULL,
  `training` varchar(255) NOT NULL,
  `weapon` varchar(64) NOT NULL,
  `weaponsNumber` varchar(64) NOT NULL,
  `equipmentSoldier` varchar(64) NOT NULL,
  `someText` varchar(64) NOT NULL,
  PRIMARY KEY (`id`)
)
